MOY/urls.py
from django.contrib import admin  # استيراد وحدة إدارة الموقع من Django
from django.urls import path, include  # استيراد الدوال المسؤولة عن تعريف المسارات وربطها
from django.conf import settings  # استيراد إعدادات المشروع
from django.conf.urls.static import static  # استيراد الدالة المسؤولة عن إعداد المسارات للملفات الثابتة والإعلامية أثناء التطوير

#from django.conf.urls.i18n import urlpatterns as i18n_urlpatterns



from django.conf.urls import handler403
from core.views import custom_403  # استدعاء الدالة من تطبيق core

handler403 = 'core.views.custom_403'


urlpatterns = [
    path('admin/', admin.site.urls), # رابط لوحة التحكم
    path('', include('core.urls')), # رابط التطبيق

    
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
   
    path('personalinfo/', include('personalinfo.urls')),
    path('hrhub/', include('hrhub.urls')),
    path('rddepartment/', include('rddepartment.urls')),



    # # path('financialaffairs/', include('financialaffairs.urls')),
    
    path('locations/', include('locations.urls')),
    path('requests_app/', include('requests_app.urls')),
     
  
]


if settings.DEBUG:  # أثناء التطوير
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
   
    pass

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import employeedashboard
from . import permissions
from . import registration
from . import profile
from . import views
from . import accountsaffairs
from .logs import personalinfo
from . import search
from .logs import rdd
from .logs import accounts
from . import employeesearch
from . import employeeactivitylog

app_name = 'accounts'


urlpatterns = [

    ################ Control Panel #################
     path('main_control_panel/', views.main_control_panel, name='main_control_panel'),

    path('main_accounts_page/', views.main_accounts_page, name='main_accounts_page'),


     path('mainemployeesearch/', employeesearch.mainemployeesearch, name='mainemployeesearch'),


    # رابط عرض تفاصيل الموظف
    path('employeedashboard/<slug:slug>/', employeedashboard.employeedashboard, name='employeedashboard'),
    path('searchemployeedashboard/<slug:slug>/', employeedashboard.searchemployeedashboard, name='searchemployeedashboard'),



    ################ Permissions #################
    path('mainlistpermissions/', permissions.mainlistpermissions, name='mainlistpermissions'),
    path('list_permissions/', permissions.list_model_permissions, name='list_permissions'),
    path('employees/<int:employee_id>/assign-permissions/', permissions.assign_permissions, name='assign_permissions'),
    path('employees/assign_bulk_permissions/', permissions.assign_bulk_permissions, name='assign_bulk_permissions'),
    path('employees/revoke_bulk_permissions/', permissions.revoke_bulk_permissions, name='revoke_bulk_permissions'),

    #################################### Registration ##############################################
     path('register_new_employee/', registration.register_new_employee, name='register_new_employee'),
     path('generate_sample_upload_employees_csv_csv/', registration.generate_sample_upload_employees_csv_csv, name='generate_sample_upload_employees_csv_csv'),
     path('upload_employees_csv/', registration.upload_employees_csv, name='upload_employees_csv'),
     path('login_view/', registration.login_view, name='login_view'),
    path('password_change/', registration.CustomPasswordChangeView.as_view(), name='password_change'),
    path('logout/', registration.logout_view, name='logout'),



    ################################### Profile #######################
    path('profile/', profile.view_profile, name='view_profile'),



     ### accountsaffairs

path('accounts_main_affiars/', accountsaffairs.accounts_main_affiars, name='accounts_main_affiars'),

    path('employee_list/', accountsaffairs.employee_list, name='employee_list'),
        path('toggle_status/<int:employee_id>/', accountsaffairs.toggle_employee_status, name='toggle_employee_status'),

    path('employee/<str:username>/login-activities/', accountsaffairs.employee_login_activity, name='employee_login_activity'),
#     path('login_activities_list/', accountsaffairs.login_activity_list, name='login_activities_list'),
    path('employee/<slug:slug>/approve/', accountsaffairs.approve_employee, name='approve_employee'),
     
     path('employee_employee_view/', accountsaffairs.employee_employee_view, name='employee_employee_view'),
    path('change-password/<int:employee_id>/', accountsaffairs.change_employee_password, name='change_employee_password'),
    path('export_filtered_employee_csv/', accountsaffairs.export_filtered_employee_csv, name='export_filtered_employee_csv'),



    
        
    path('basic_info_change_log/', personalinfo.basic_info_change_log, name='basic_info_change_log'),
     path('officialtypeslogs/', personalinfo.officialtypeslogs, name='officialtypeslogs'),
    path('emploeeofficialdoc/', personalinfo.emploeeofficialdoc, name='emploeeofficialdoc'),
    path('religionchangelog/', personalinfo.religionchangelog, name='religionchangelog'),
    path('nationalismchangelog/', personalinfo.nationalismchangelog, name='nationalismchangelog'),
    path('additionalinfochangelog/', personalinfo.additionalinfochangelog, name='additionalinfochangelog'),

    path('educationdegreetypechangelog/', rdd.educationdegreetypechangelog, name='educationdegreetypechangelog'),
    path('collegechangelog/', rdd.collegechangelog, name='collegechangelog'),
    path('foreignuniversitychangelog/', rdd.foreignuniversitychangelog, name='foreignuniversitychangelog'),
        path('employeeeducationchangelog/', rdd.employeeeducationchangelog, name='employeeeducationchangelog'),
        
    # path('employeechangelog/', accounts.employeechangelog, name='employeechangelog'),

    




    ############################# Search #######
     path('mainemplpyeesearch/', search.mainemplpyeesearch, name='mainemplpyeesearch'),


     ########################## Resset Password ##################
#       path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset_by_employee_id'),
#     path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
# path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
#         template_name='registration/password_reset_confirm.html'
#     ), name='password_reset_confirm'),    
#     path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('employee_activity_view/', employeeactivitylog.employee_activity_view, name='employee_activity_view'),
    path('employee_activity/<slug:slug>/activity/', employeeactivitylog.employee_activity, name='employee_activity'),
    path('make_superuser/<int:employee_id>/', permissions.make_superuser, name='make_superuser'),

]

hrhub/urls.py
from django.urls import path
from . import views
from . import employeegradestep
from . import employement
from . import thanks
from . import punishments
from . import leave
from . import jobtitle
from . import duty_assignment_order 
from . import places_of_employment
from . import placement
from . import office_positions
from . import staffing_structure
from . import central_alloc
from . import employmenthistory
from . import absences
from . import employee_office

app_name = 'hrhub'
urlpatterns = [

     path('main_hrhub/', views.main_hrhub, name='main_hrhub'),

   
    ##########################  Job Title ###########################

    path('main_job_title/', jobtitle.main_job_title, name='main_job_title'),
    path('sub_job_titles/<slug:parent_slug>/', jobtitle.sub_job_titles, name='sub_job_titles'),
    path('add_job_title/', jobtitle.add_job_title, name='add_job_title'),
    path('update_job_title/<slug:slug>/', jobtitle.update_job_title, name='update_job_title'),  # تعديل هنا لاستخدام slug
    path('job_title_detail/<slug:slug>/', jobtitle.job_title_detail, name='job_title_detail'),  # مسار عرض التفاصيل
    path('job_title/delete/<slug:slug>/', jobtitle.delete_job_title, name='delete_job_title'),
        path('upload_job_titles_csv/', jobtitle.upload_job_titles_csv, name='upload_job_titles_csv'),

    
                    ###### Emplyee job title #######
    path('main_employee_job_title/', jobtitle.main_employee_job_title, name='main_employee_job_title'),
   
    path('create_employee_job_title/create/<slug:slug>/', jobtitle.create_employee_job_title, name='create_employee_job_title'),
    path('get-child-job-titles/<int:parent_id>/', jobtitle.get_child_job_titles, name='get_child_job_titles'),
    path('get-related-job-titles/<int:job_title_id>/', jobtitle.get_related_job_titles, name='get_related_job_titles'),
    path('employee_job_titles/<slug:slug>/', jobtitle.employee_job_titles, name='employee_job_titles'),

    path('employee_job_titlesemployee/<slug:slug>/', jobtitle.employee_job_titlesemployee, name='employee_job_titlesemployee'),

    path('update_employee_job_title/<slug:slug>/', jobtitle.update_employee_job_title, name='update_employee_job_title'),
    path('delete_employee_job_title/<slug:slug>/', jobtitle.delete_employee_job_title, name='delete_employee_job_title'),
    path('update_employee_job_title_settings/', jobtitle.update_employee_job_title_settings, name='update_employee_job_title_settings'),
    path('upload_employee_job_titles_csv/', jobtitle.upload_employee_job_titles_csv, name='upload_employee_job_titles_csv'),
    path('employee_job_title_detail/<slug:slug>/', jobtitle.employee_job_title_detail, name='employee_job_title_detail'),

    path('update_employee_job_title_settings/', jobtitle.update_employee_job_title_settings, name='update_employee_job_title_settings'),




#     #######################  Duty assignment order ########################

    path('main_duty_assignment_order/', duty_assignment_order.main_duty_assignment_order, name='main_duty_assignment_order'),
    path('add_duty_assignment_order/', duty_assignment_order.add_duty_assignment_order, name='add_duty_assignment_order'),
    path('duty_assignment_order_detail/<slug:slug>/', duty_assignment_order.duty_assignment_order_detail, name='duty_assignment_order_detail'),  # مسار عرض التفاصيل
    path('update_duty_assignment_order/<slug:slug>/', duty_assignment_order.update_duty_assignment_order, name='update_duty_assignment_order'),  # تعديل هنا لاستخدام slug
    path('delete_duty_assignment_order/<slug:slug>/', duty_assignment_order.delete_duty_assignment_order, name='delete_duty_assignment_order'), 



 ############################################## employeegradestep #######################
                ############### Grade ################
     path('main_employee_grade/', employeegradestep.main_employee_grade, name='main_employee_grade'),
      path('employee_grade_create/', employeegradestep.employee_grade_create, name='employee_grade_create'),
      path('grade_detail/<slug:slug>/',employeegradestep.grade_detail, name='grade_detail'),
    path('update_employee_grade/<slug:slug>/',employeegradestep.update_employee_grade, name='update_employee_grade'),
    path('delete_employee_grade/<slug:slug>/',employeegradestep.delete_employee_grade, name='delete_employee_grade'),
         path('upload_employee_grades_csv/', employeegradestep.upload_employee_grades_csv, name='upload_employee_grades_csv'),

    
    
#                 ############### Step ################   
    path('main_employee_step/', employeegradestep.main_employee_step, name='main_employee_step'),
    path('employee_step_create/', employeegradestep.employee_step_create, name='employee_step_create'),
    path('step_detail/<slug:slug>/', employeegradestep.step_detail, name='step_detail'),
    path('update_employee_step/<slug:slug>/update/', employeegradestep.update_employee_step, name='update_employee_step'),
    path('delete_employee_step/<slug:slug>/delete/', employeegradestep.delete_employee_step, name='delete_employee_step'),
        path('upload_employee_steps_csv/', employeegradestep.upload_employee_steps_csv, name='upload_employee_steps_csv'),


#     ####################### Thankks #######################
        path('main_employeethanks/', thanks.main_employeethanks, name='main_employeethanks'),
        path('add_thanks_to_employees/', thanks.add_thanks_to_employees, name='add_thanks_to_employees'),
        path('save_thanks/', thanks.save_thanks, name='save_thanks'),
        path('employee_thanks_list/<slug:slug>/', thanks.employee_thanks_list, name='employee_thanks_list'),

        path('employee_thanks_listemployee/<slug:slug>/', thanks.employee_thanks_listemployee, name='employee_thanks_listemployee'),

        path('delete_employee_thanks/<slug:slug>/', thanks.delete_employee_thanks, name='delete_employee_thanks'),
        path('update_employee_thanks/<slug:slug>/', thanks.update_employee_thanks, name='update_employee_thanks'),
        path('upload_employee_thanks_csv/', thanks.upload_employee_thanks_csv, name='upload_employee_thanks_csv'),
        path('download_thanks_csv_template/', thanks.download_thanks_csv_template, name='download_thanks_csv_template'),

#     path('employee/<slug:slug>/thanks/', thanks.employee_thanks_view, name='employee_thanks_view'),

    path('main_thanks_type/', thanks.main_thanks_type, name='main_thanks_type'),
    path('add_thanks_type/', thanks.add_thanks_type, name='add_thanks_type'),
    path('update_thanks_type/<slug:slug>/', thanks.update_thanks_type, name='update_thanks_type'),  # تعديل هنا لاستخدام slug
    path('thanks_type_detail/<slug:slug>/', thanks.thanks_type_detail, name='thanks_type_detail'),  # مسار عرض التفاصيل
    path('delete_thanks_type/delete/<slug:slug>/', thanks.delete_thanks_type, name='delete_thanks_type'),



#     ######################## Punishments #######################


         path('main_punishment_types/', punishments.main_punishment_types, name='main_punishment_types'),
         path('add_punishment_type/', punishments.add_punishment_type, name='add_punishment_type'),
         path('punishment_type_detail/<slug:slug>/', punishments.punishment_type_detail, name='punishment_type_detail'),
         path('update_punishment_type/<slug:slug>/edit/', punishments.update_punishment_type, name='update_punishment_type'),
         path('delete_punishment_type/<slug:slug>/delete/', punishments.delete_punishment_type, name='delete_punishment_type'),

         ############## Employee ##########
        path('main_employee_punishments/', punishments.main_employee_punishments, name='main_employee_punishments'),
        path('add_punishments_to_employees/', punishments.add_punishments_to_employees, name='add_punishments_to_employees'),
        path('save_punishments/', punishments.save_punishments, name='save_punishments'),
        path('employee_punishments_list/<slug:slug>/', punishments.employee_punishments_list, name='employee_punishments_list'),

        path('employee_punishments_listemployee/<slug:slug>/', punishments.employee_punishments_listemployee, name='employee_punishments_listemployee'),
        path('download_punishment_csv_template/', punishments.download_punishment_csv_template, name='download_punishment_csv_template'),



        path('delete_employee_punishment/<slug:slug>/', punishments.delete_employee_punishment, name='delete_employee_punishment'),
    path('update_employee_punishment/<slug:slug>/', punishments.update_employee_punishment, name='update_employee_punishment'),
    path('upload_employee_punishment_csv/', punishments.upload_employee_punishment_csv, name='upload_employee_punishment_csv'),


    


         

    
#     ######################## Leave #######################

#     ################## Leave type
     path('main_leave_type/', leave.main_leave_type, name='main_leave_type'),
     path('add_leave_type/', leave.add_leave_type, name='add_leave_type'),
     path('leave_type/<slug:slug>/', leave.leave_type_detail, name='leave_type_detail'),
     path('update_leave_type/<slug:slug>/', leave.update_leave_type, name='update_leave_type'),
      path('delete_leave_type/<slug:slug>/', leave.delete_leave_type, name='delete_leave_type'),

#      ################### Leave Balane #######################
       path('main_leave_balance/', leave.main_leave_balance, name='main_leave_balance'),
       path('create_leave_balance/<slug:slug>/', leave.create_leave_balance, name='create_leave_balance'),
       path('employee_leave_balances/<slug:slug>/', leave.employee_leave_balances, name='employee_leave_balances'),
       path('update_leave_balance_view/<slug:slug>/', leave.update_leave_balance_view, name='update_leave_balance_view'),
       path('delete_leave_balance/<slug:slug>/', leave.delete_leave_balance, name='delete_leave_balance'),
        path('upload_leave_balance_csv/', leave.upload_leave_balance_csv, name='upload_leave_balance_csv'),



       

accounts/templates/accounts/employeedashboard/employeedashboarddetail.html
{% extends 'core/base.html' %}

{% block searchbar %}

{% endblock %}

{% block titlecontent %}
{% endblock %}

{% block content %}

<h2>معلومات الموظف</h2>
    
    <p><strong> الرقم الوظيفي:</strong> {{ employee.username }}</p>
    {% if basic_info %}
    

    <div class="personal-info-container">
        
        <p><strong>الاسم الثلاثي:</strong> {{ basic_info.get_full_name }} 
        
    </p>

    <p><strong>اسم الوالدة :</strong> {{ basic_info.mothername }} 
       
    </p>
    <p><strong>رقم الهاتف  :</strong> {{ basic_info.phone_number }} 
        
    </p>
    
    <p><strong>البريد الالكتروني   :</strong> {{ basic_info.email }} 
       
    </p>
    
    <p><strong> تاريخ الميلاد   :</strong> {{ basic_info.date_of_birth }} 
       
    </p>


<p><strong> عمر الموظف    :</strong> {{ basic_info.emplpyee_age }} </p>

<p><strong> محل الميلاد   :</strong> {{ basic_info.place_of_birth.name_arabic }} 
    <p><strong>  الجنس   :</strong> {{ basic_info.get_gender_display }} 
      
    </p>



<p><strong>  السيرة الذاتية   :</strong> {{ basic_info.bio }} 
   
</p>

<p><strong>  تحديث المعلومات الاساسية    :</strong>  <a href="{% url 'personalinfo:updatebasicinfo' basic_info.slug %}" >تحديث معلومات أساسية</a>   

</p>

    </div> 

   



    <div class="personal-info-container">
        {% if additional_info %}

        <p><strong>فصيلة الدم:</strong> {{ additional_info.blood_type }}</p> 


        <p><strong>الديانة:</strong> {{ additional_info.religion.name_in_arabic }}  </p> 


        <p><strong>القومية:</strong> {{ additional_info.nationalism.name_in_arabic }}  </p> 
        <p><strong>الحالة الاجتماعية:</strong> {{ additional_info.get_marital_status_display }} </p> 
        <p><strong>المحافظة:</strong> {{ additional_info.governorate_of_residence.name_arabic }}
           </p> 

           <p><strong>العنوان:</strong> {{ additional_info.address }}  </p> 
           <p><strong>اسم الطوارئ:</strong> {{ additional_info.emergency_contact_name }}
            </p> 
            <p><strong>رقم الطوارئ:</strong> {{ additional_info.emergency_contact_number }}</p>


<p><strong>  تحديث المعلومات الاضافية    :</strong>  <a href="{% url 'personalinfo:update_additional_info' additional_info.slug %}" >تحديث معلومات الاضافية</a>   

</p>


{% else %}
لا يوجد معلومات اضافية -  <a href="{% url 'personalinfo:add_additional_info' employee.basic_info.slug %}">إضافة معلومات إضافية</a>
{% endif %}
    
    </div> 







{% else %}
لا يوجد معلومات اساسية  <a href="{% url 'personalinfo:addbasicinfo' employee.slug %}" class="update_button">إضافة معلومات أساسية</a>   
{% endif %}
    


{% endblock %}

{% block pagination %}

{% endblock %}

{% block titlesidemenu %}
{% endblock %}



{% block sidemenu %}

<div class="button-container">
    <a href="{% url 'accounts:view_profile' %}" class="custom-button">الصفحة الشخصية</a>
    {% if user.is_superuser %}
    <a href="{% url 'accounts:main_control_panel' %}" class="custom-button">لوحة التحكم</a>
    
    {% endif %}
    {% if basic_info %}

    <a href="{% url 'personalinfo:employee_documents' basic_info.slug%}" class="custom-button"> الوثائق الرسمية   </a>
    <a href="{% url 'rddepartment:employeeeducation_detail' basic_info.slug%}" class="custom-button"> الشهادات الاكاديمية </a>
    <a href="{% url 'rddepartment:all_employee_certificates' basic_info.slug%}" class="custom-button"> الشهادات غير الاكاديمية </a>

    <a href="{% url 'hrhub:employee_thanks_list' basic_info.slug%}" class="custom-button"> كتب الشكر والتقدير   </a>

    <a href="{% url 'hrhub:employee_punishments_list' basic_info.slug%}" class="custom-button"> كتب العقوبة    </a>

    <a href="{% url 'hrhub:employee_leave_requests' basic_info.slug%}" class="custom-button"> الاجازات     </a>


    <a href="{% url 'hrhub:all_placement_detail' basic_info.slug%}" class="custom-button"> التنسيبات     </a>

    <a href="{% url 'hrhub:employee_offices_view' basic_info.slug%}" class="custom-button"> دوائر الموظف     </a>


    <a href="{% url 'hrhub:list_employee_office_positions' basic_info.slug%}" class="custom-button"> المناصب      </a>

    <a href="{% url 'hrhub:employee_absence_list' basic_info.slug%}" class="custom-button"> غيابات الموظف      </a>

    <a href="{% url 'hrhub:employment_history_detail' basic_info.slug%}" class="custom-button"> التاريخ الوظيفي       </a>



    
    
    <a href="{% url 'hrhub:employee_job_titles' basic_info.slug%}" class="custom-button"> العنوان الوظيفي   </a>


    {% endif %}
    
</div>



{% endblock %}



{% block leftsidemenu %}
{% if basic_info%}
<div class="leftsidemenu-container">
    {% if basic_info and basic_info.avatar %}
        <div class="avatar-wrapper">
            <img src="{{ basic_info.avatar.url }}" alt="{{ basic_info.get_full_name }}'s avatar" class="avatar-image">
        </div>

       
    {% else %}
        <p class="no-avatar">لا توجد صورة 
          
        </p>
    {% endif %}
</div>

<label class="result-label"> 
    نوع الملاك:
    {% if latest_staff_type %}
    {{ latest_staff_type.employee_staff_type.name_in_arabic }}
    {% else %}
       غير متوفر    
    {% endif %}
 </label>
 <label class="result-label"> 
 كتب الشكر والتقدير: {{ thanks_count }}
 </label>

 <label class="result-label"> 
    عدد كــتب العقــوبة: {{ punishments_count }}
</label>

<label class="result-label"> 
    عدد غيابات الموظف: {{ absences_count }}
</label>

 {% endif %}
{% endblock %}

accounts/templates/accounts/employeedashboard/searchemployeedashboard.html
{% extends 'core/base.html' %}

{% block searchbar %}

{% endblock %}

{% block titlecontent %}
{% endblock %}

{% block content %}

<h2>معلومات الموظف</h2>
    
    <p><strong> الرقم الوظيفي:</strong> {{ employee.username }}</p>
    {% if basic_info %}
    <div class="personal-info-container">
        <p><strong>الاسم الثلاثي:</strong> {{ basic_info.get_full_name }} 
        
    </p>

    <p><strong>اسم الوالدة :</strong> {{ basic_info.mothername }} 
       
    </p>
    <p><strong>رقم الهاتف  :</strong> {{ basic_info.phone_number }} 
        
    </p>
    
    <p><strong>البريد الالكتروني   :</strong> {{ basic_info.email }} 
       
    </p>
    
    <p><strong> تاريخ الميلاد   :</strong> {{ basic_info.date_of_birth }} 
       
    </p>


<p><strong> عمر الموظف    :</strong> {{ basic_info.emplpyee_age }} </p>

<p><strong> محل الميلاد   :</strong> {{ basic_info.place_of_birth.name_arabic }} 
    <p><strong>  الجنس   :</strong> {{ basic_info.get_gender_display }} 
      
    </p>



<p><strong>  السيرة الذاتية   :</strong> {{ basic_info.bio }} 
   
</p>


</p>

    </div> 

    


    <div class="personal-info-container">
        {% if additional_info %}

        <p><strong>فصيلة الدم:</strong> {{ additional_info.blood_type }}</p> 


        <p><strong>الديانة:</strong> {{ additional_info.religion.name_in_arabic }}  </p> 


        <p><strong>القومية:</strong> {{ additional_info.nationalism.name_in_arabic }}  </p> 
        <p><strong>الحالة الاجتماعية:</strong> {{ additional_info.get_marital_status_display }} </p> 
        <p><strong>المحافظة:</strong> {{ additional_info.governorate_of_residence.name_arabic }}
           </p> 

           <p><strong>العنوان:</strong> {{ additional_info.address }}  </p> 
           <p><strong>اسم الطوارئ:</strong> {{ additional_info.emergency_contact_name }}
            </p> 
            <p><strong>رقم الطوارئ:</strong> {{ additional_info.emergency_contact_number }}</p>


{% else %}
لا يوجد معلومات اضافية - يرجى الاتصال بالقسم المختص
{% endif %}
    
    </div> 







{% else %}
لا يوجد معلومات اساسية - يرجى الاتصال بالقسم المختص
{% endif %}
    


{% endblock %}

{% block pagination %}

{% endblock %}

{% block titlesidemenu %}
{% endblock %}



{% block sidemenu %}

<div class="button-container">
    <a href="{% url 'accounts:view_profile' %}" class="custom-button">الصفحة الشخصية</a>
    {% if user.is_superuser %}
    <a href="{% url 'accounts:main_control_panel' %}" class="custom-button">لوحة التحكم</a>
    
    {% endif %}
    {% if basic_info %}

    <a href="{% url 'personalinfo:employee_documents_employee' basic_info.slug%}" class="custom-button"> الوثائق الرسمية   </a>
    <a href="{% url 'rddepartment:employeeeducation_detail_employee' basic_info.slug%}" class="custom-button"> الشهادات الاكاديمية </a>
    <a href="{% url 'rddepartment:all_employee_certificates_employee' basic_info.slug%}" class="custom-button"> الشهادات غير الاكاديمية </a>

    <a href="{% url 'hrhub:employee_thanks_listemployee' basic_info.slug%}" class="custom-button"> كتب الشكر والتقدير   </a>

    <a href="{% url 'hrhub:employee_punishments_listemployee' basic_info.slug%}" class="custom-button"> كتب العقوبة    </a>

    <a href="{% url 'hrhub:employee_leave_requestsemployee' basic_info.slug%}" class="custom-button"> الاجازات     </a>


    <a href="{% url 'hrhub:all_placement_detailemployee' basic_info.slug%}" class="custom-button"> التنسيبات     </a>

    <a href="{% url 'hrhub:employee_offices_viewemployee' basic_info.slug%}" class="custom-button"> دوائر الموظف     </a>


    <a href="{% url 'hrhub:list_employee_office_positionsemployee' basic_info.slug%}" class="custom-button"> المناصب      </a>

    <a href="{% url 'hrhub:employee_absence_listemployee' basic_info.slug%}" class="custom-button"> غيابات الموظف      </a>


    <a href="{% url 'hrhub:employment_history_detailemployee' basic_info.slug%}" class="custom-button"> التاريخ الوظيفي       </a>


    
    
    <a href="{% url 'hrhub:employee_job_titlesemployee' basic_info.slug%}" class="custom-button"> العنوان الوظيفي   </a>


    {% endif %}
    
</div>



{% endblock %}



{% block leftsidemenu %}
{% if basic_info%}
<div class="leftsidemenu-container">
    {% if basic_info and basic_info.avatar %}
        <div class="avatar-wrapper">
            <img src="{{ basic_info.avatar.url }}" alt="{{ basic_info.get_full_name }}'s avatar" class="avatar-image">
        </div>

       
    {% else %}
        <p class="no-avatar">لا توجد صورة 
          
        </p>
    {% endif %}
</div>

<label class="result-label"> 
    نوع الملاك:
    {% if latest_staff_type %}
    {{ latest_staff_type.employee_staff_type.name_in_arabic }}
    {% else %}
       غير متوفر    
    {% endif %}
 </label>
 <label class="result-label"> 
 كتب الشكر والتقدير: {{ thanks_count }}
 </label>

 <label class="result-label"> 
    عدد كــتب العقــوبة: {{ punishments_count }}
</label>

<label class="result-label"> 
    عدد غيابات الموظف: {{ absences_count }}
</label>

 {% endif %}
{% endblock %}