MOY/urls.py
from django.contrib import admin  # استيراد وحدة إدارة الموقع من Django
from django.urls import path, include  # استيراد الدوال المسؤولة عن تعريف المسارات وربطها
from django.conf import settings  # استيراد إعدادات المشروع
from django.conf.urls.static import static  # استيراد الدالة المسؤولة عن إعداد المسارات للملفات الثابتة والإعلامية أثناء التطوير

#from django.conf.urls.i18n import urlpatterns as i18n_urlpatterns



from django.conf.urls import handler403
from core.views import custom_403  # استدعاء الدالة من تطبيق core

handler403 = 'core.views.custom_403'


urlpatterns = [
    path('admin/', admin.site.urls), # رابط لوحة التحكم
    path('', include('core.urls')), # رابط التطبيق

    
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
   
    path('personalinfo/', include('personalinfo.urls')),
    path('hrhub/', include('hrhub.urls')),
    path('rddepartment/', include('rddepartment.urls')),



    # # path('financialaffairs/', include('financialaffairs.urls')),
    
    path('locations/', include('locations.urls')),
    path('requests_app/', include('requests_app.urls')),
     
  
]


if settings.DEBUG:  # أثناء التطوير
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
   
    pass

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import employeedashboard
from . import permissions
from . import registration
from . import profile
from . import views
from . import accountsaffairs
from .logs import personalinfo
from . import search
from .logs import rdd
from .logs import accounts
from . import employeesearch
from . import employeeactivitylog

app_name = 'accounts'


urlpatterns = [

    ################ Control Panel #################
     path('main_control_panel/', views.main_control_panel, name='main_control_panel'),

    path('main_accounts_page/', views.main_accounts_page, name='main_accounts_page'),


     path('mainemployeesearch/', employeesearch.mainemployeesearch, name='mainemployeesearch'),


    # رابط عرض تفاصيل الموظف
    path('employeedashboard/<slug:slug>/', employeedashboard.employeedashboard, name='employeedashboard'),
    path('searchemployeedashboard/<slug:slug>/', employeedashboard.searchemployeedashboard, name='searchemployeedashboard'),



    ################ Permissions #################
    path('mainlistpermissions/', permissions.mainlistpermissions, name='mainlistpermissions'),
    path('list_permissions/', permissions.list_model_permissions, name='list_permissions'),
    path('employees/<int:employee_id>/assign-permissions/', permissions.assign_permissions, name='assign_permissions'),
    path('employees/assign_bulk_permissions/', permissions.assign_bulk_permissions, name='assign_bulk_permissions'),
    path('employees/revoke_bulk_permissions/', permissions.revoke_bulk_permissions, name='revoke_bulk_permissions'),

    #################################### Registration ##############################################
     path('register_new_employee/', registration.register_new_employee, name='register_new_employee'),
     path('generate_sample_upload_employees_csv_csv/', registration.generate_sample_upload_employees_csv_csv, name='generate_sample_upload_employees_csv_csv'),
     path('upload_employees_csv/', registration.upload_employees_csv, name='upload_employees_csv'),
     path('login_view/', registration.login_view, name='login_view'),
    path('password_change/', registration.CustomPasswordChangeView.as_view(), name='password_change'),
    path('logout/', registration.logout_view, name='logout'),



    ################################### Profile #######################
    path('profile/', profile.view_profile, name='view_profile'),



     ### accountsaffairs

path('accounts_main_affiars/', accountsaffairs.accounts_main_affiars, name='accounts_main_affiars'),

    path('employee_list/', accountsaffairs.employee_list, name='employee_list'),
        path('toggle_status/<int:employee_id>/', accountsaffairs.toggle_employee_status, name='toggle_employee_status'),

    path('employee/<str:username>/login-activities/', accountsaffairs.employee_login_activity, name='employee_login_activity'),
#     path('login_activities_list/', accountsaffairs.login_activity_list, name='login_activities_list'),
    path('employee/<slug:slug>/approve/', accountsaffairs.approve_employee, name='approve_employee'),
     
     path('employee_employee_view/', accountsaffairs.employee_employee_view, name='employee_employee_view'),
    path('change-password/<int:employee_id>/', accountsaffairs.change_employee_password, name='change_employee_password'),
    path('export_filtered_employee_csv/', accountsaffairs.export_filtered_employee_csv, name='export_filtered_employee_csv'),



    
        
    path('basic_info_change_log/', personalinfo.basic_info_change_log, name='basic_info_change_log'),
     path('officialtypeslogs/', personalinfo.officialtypeslogs, name='officialtypeslogs'),
    path('emploeeofficialdoc/', personalinfo.emploeeofficialdoc, name='emploeeofficialdoc'),
    path('religionchangelog/', personalinfo.religionchangelog, name='religionchangelog'),
    path('nationalismchangelog/', personalinfo.nationalismchangelog, name='nationalismchangelog'),
    path('additionalinfochangelog/', personalinfo.additionalinfochangelog, name='additionalinfochangelog'),

    path('educationdegreetypechangelog/', rdd.educationdegreetypechangelog, name='educationdegreetypechangelog'),
    path('collegechangelog/', rdd.collegechangelog, name='collegechangelog'),
    path('foreignuniversitychangelog/', rdd.foreignuniversitychangelog, name='foreignuniversitychangelog'),
        path('employeeeducationchangelog/', rdd.employeeeducationchangelog, name='employeeeducationchangelog'),
        
    # path('employeechangelog/', accounts.employeechangelog, name='employeechangelog'),

    




    ############################# Search #######
     path('mainemplpyeesearch/', search.mainemplpyeesearch, name='mainemplpyeesearch'),


     ########################## Resset Password ##################
#       path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset_by_employee_id'),
#     path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
# path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
#         template_name='registration/password_reset_confirm.html'
#     ), name='password_reset_confirm'),    
#     path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('employee_activity_view/', employeeactivitylog.employee_activity_view, name='employee_activity_view'),
    path('employee_activity/<slug:slug>/activity/', employeeactivitylog.employee_activity, name='employee_activity'),
    path('make_superuser/<int:employee_id>/', permissions.make_superuser, name='make_superuser'),

]

personalinfo/urls.py
from django.urls import path
from . import nationalism
# from .views import religion_change_log_list
from .import basicinfo
from .import religion
from . import officialdocumentstype
from . import additionainfo
from . import employeeofficialdocuments
from . import views


app_name = 'personalinfo'

urlpatterns = [

    ######################### main_personalinfo ##########################

    path('main_personalinfo/', views.main_personalinfo, name='main_personalinfo'),

    ############################### main_basicinfo ###############################
    path('mainbasicinfo/', basicinfo.mainbasicinfo, name='mainbasicinfo'),
    path('addbasicinfo/<slug:slug>/', basicinfo.addbasicinfo, name='addbasicinfo'),
    path('upload_basic_info_csv/', basicinfo.upload_basic_info_csv, name='upload_basic_info_csv'),
    path('download_sample_basic_info_csv/', basicinfo.download_sample_basic_info_csv, name='download_sample_basic_info_csv'),
    # path('employees/<slug:slug>/add_basic_info/', basicinfo.add_basic_info, name='add_basic_info'),
    path('basicinfodetail/<slug:slug>/', basicinfo.basicinfodetail, name='basicinfodetail'),
     path('updatebasicinfo/<slug:slug>/', basicinfo.updatebasicinfo, name='updatebasicinfo'),
    path('export_basic_info_to_csv/', basicinfo.export_basic_info_to_csv, name='export_basic_info_to_csv'),
    
    path('deletedetailsbasicinfo/<slug:slug>/', basicinfo.deletedetailsbasicinfo, name='deletedetailsbasicinfo'),

########################################### Update Basic info ##############################

    path('basicinfo/update_firstname/<slug:slug>/', basicinfo.update_firstname, name='update_firstname'),
    path('basicinfo/update_secondname/<slug:slug>/', basicinfo.update_secondname, name='update_secondname'),
    path('basicinfo/update_thirdname/<slug:slug>/', basicinfo.update_thirdname, name='update_thirdname'),
    path('basicinfo/update_fourthname/<slug:slug>/', basicinfo.update_fourthname, name='update_fourthname'),
    path('basicinfo/update_surname/<slug:slug>/', basicinfo.update_surname, name='update_surname'),
    path('basicinfo/update_mother_name/<slug:slug>/', basicinfo.update_mother_name, name='update_mother_name'),
    path('basicinfo/update_phone_number/<slug:slug>/', basicinfo.update_phone_number, name='update_phone_number'),
    path('basicinfo/update_email/<slug:slug>/', basicinfo.update_email, name='update_email'),
    path('update_date_of_birth/<slug:slug>/', basicinfo.update_date_of_birth, name='update_date_of_birth'),
    path('update_place_of_birth/<slug:slug>/', basicinfo.update_place_of_birth, name='update_place_of_birth'),
        path('update_gender/<slug:slug>/', basicinfo.update_gender, name='update_gender'),
            path('update_bio/<slug:slug>/', basicinfo.update_bio, name='update_bio'),
                path('update_avatar/<slug:slug>/', basicinfo.update_avatar, name='update_avatar'),





    ########################## Update Additional Info ############################
    path('update_blood_type/<slug:slug>/', additionainfo.update_blood_type, name='update_blood_type'),
    path('update_employee_religion/<slug:slug>/', additionainfo.update_employee_religion, name='update_employee_religion'),
    path('update_nationalism/<slug:slug>/', additionainfo.update_nationalism, name='update_nationalism'),
    path('update_marital_status/<slug:slug>/', additionainfo.update_marital_status, name='update_marital_status'),
    path('update_governorate_of_residence/<slug:slug>/', additionainfo.update_governorate_of_residence, name='update_governorate_of_residence'),
    path('update_address/<slug:slug>/', additionainfo.update_address, name='update_address'),
    path('update_emergency_contact/<slug:slug>/', additionainfo.update_emergency_contact, name='update_emergency_contact'),





    # path('basic-info/toggle-approval/<slug:slug>/', basicinfo.toggle_approval, name='toggle_approval'),
    #  path('export_basic_info_csv/', basicinfo.export_basic_info_csv, name='export_basic_info_csv'),



    

    # path('details_update_basic_info/<slug:slug>/', basicinfo.details_update_basic_info, name='details_update_basic_info'),

######################## Statistics ############################
    #  path('get_statistical_data/', basicinfo.get_statistical_data, name='get_statistical_data'),





    ################################ Update Basic Info ################################

    ###### Dash board ########
    # path('personalinfo/update_basic_info_dash_board/<slug:slug>/', basicinfo.update_basic_info_dash_board, name='update_basic_info_dash_board'),


    # path('basicinfo/update_firstname/<slug:slug>/', basicinfo.update_firstname, name='update_firstname'),
    # path('basicinfo/update_secondname/<slug:slug>/', basicinfo.update_secondname, name='update_secondname'),
    # path('basicinfo/update_thirdname/<slug:slug>/', basicinfo.update_thirdname, name='update_thirdname'),
    # path('basicinfo/update_fourthname/<slug:slug>/', basicinfo.update_fourthname, name='update_fourthname'),
    # path('basicinfo/update_surname/<slug:slug>/', basicinfo.update_surname, name='update_surname'),
    # path('basicinfo/update_mother_name/<slug:slug>/', basicinfo.update_mother_name, name='update_mother_name'),
    # path('basicinfo/update_phone_number/<slug:slug>/', basicinfo.update_phone_number, name='update_phone_number'),
    # path('basicinfo/update_email/<slug:slug>/', basicinfo.update_email, name='update_email'),
    # path('update_date_of_birth/<slug:slug>/', basicinfo.update_date_of_birth, name='update_date_of_birth'),
    # path('update_place_of_birth/<slug:slug>/', basicinfo.update_place_of_birth, name='update_place_of_birth'),
    #     path('update_gender/<slug:slug>/', basicinfo.update_gender, name='update_gender'),
    #         path('update_bio/<slug:slug>/', basicinfo.update_bio, name='update_bio'),
    #             path('update_avatar/<slug:slug>/', basicinfo.update_avatar, name='update_avatar'),

    ################################ additional  Info ################################
    



    # URL لعرض سجلات الحركة باستخدام الـ slug


    # ######################## Religion
    path('mainreligion/', religion.mainreligion, name='mainreligion'),
    path('add_religion/', religion.add_religion, name='add_religion'),
    path('religion_detail/<slug:slug>/', religion.religion_detail, name='religion_detail'),
    path('update_religion/<slug:slug>/', religion.update_religion, name='update_religion'),
    path('religion/delete/<slug:slug>/', religion.delete_religion, name='delete_religion'),
    path('export_religions_csv/', religion.export_religions_csv, name='export_religions_csv'),

    
    # path('religion/<slug:slug>/', religion_change_log_list, name='religion_change_logs'),
    #################### Religion Statistics #####################
    # path('export_religion_csv/', religion.export_religion_csv, name='export_religion_csv'),




    ############################## nationalism ##############################
    path('nationalism/<slug:slug>/logs/', nationalism.nationalism_change_logs, name='nationalism_change_logs'),
    path('main_nationalism/', nationalism.main_nationalism, name='main_nationalism'),
    path('nationalism/add/', nationalism.add_nationalism, name='add_nationalism'),
    path('nationalism_detail/<slug:slug>/', nationalism.nationalism_detail, name='nationalism_detail'),
    path('main_update_nationalism/<slug:slug>/', nationalism.main_update_nationalism, name='main_update_nationalism'),
    path('nationalism/delete/<slug:slug>/', nationalism.delete_nationalism, name='delete_nationalism'),
    path('export_nationalism_csv/', nationalism.export_nationalism_csv, name='export_nationalism_csv'),


     # #################### Additionalinfo ####################

    path('main_additionainfo/', additionainfo.main_additionainfo, name='main_additionainfo'),
    path('add_additional_info/<slug:slug>/', additionainfo.add_additional_info, name='add_additional_info'),
    path('additional_info_detail/<slug:slug>/',additionainfo.additional_info_detail, name='additional_info_detail'),
    path('update_additional_info/<slug:slug>/',additionainfo.update_additional_info, name='update_additional_info'),
    path('delete_additional_info/<slug:slug>/', additionainfo.delete_additional_info, name='delete_additional_info'),
    path('download_sample_additional_info_csv/', additionainfo.download_sample_additional_info_csv, name='download_sample_additional_info_csv'),
    path('upload_additionalinfo_csv/', additionainfo.upload_additional_info_csv, name='upload_additionalinfo_csv'),
    path('export_additional_info_to_csv/', additionainfo.export_additional_info_to_csv, name='export_additional_info_to_csv'),


    

    # path('export_additional_info_csv/', additionalInfo.export_additional_info_csv, name='export_additional_info_csv'),
    # path('download_sample_additional_info_csv/', additionalInfo.download_sample_additional_info_csv, name='download_sample_additional_info_csv'),
    # path('upload_additionalinfo_csv/', additionalInfo.upload_additional_info_csv, name='upload_additionalinfo_csv'),
    # path('additional_info_detail/<slug:slug>/',additionalInfo.additional_info_detail, name='additional_info_detail'),
    # path('update_additional_info/<slug:slug>/',additionalInfo.update_additional_info, name='update_additional_info'),
    # path('delete/<slug:slug>/', additionalInfo.delete_additional_info, name='delete_additional_info'),
    #     path('statistics_additional-info/', additionalInfo.additional_info_statistics_view, name='additional_info_statistics'),


    ########################## Update Additional Info ############################
    # path('update_blood_type/<slug:slug>/', additionalInfo.update_blood_type, name='update_blood_type'),
    # path('update_employee_religion/<slug:slug>/', additionalInfo.update_employee_religion, name='update_employee_religion'),

accounts/templates/accounts/accountsaffairs/accounts_main_affiars.html
{% extends 'core/base.html' %}

{% block searchbar %}
<form method="get" action="">
    <div class="main_searchbar">
        <div class="grid-container">
            <!-- البحث حسب الرقم الوظيفي -->
            <div class="grid-item input-container">
                <input type="text" id="username" name="username" placeholder="ادخل الرقم الوظيفي" value="{{ request.GET.username }}">
            </div>
            <!-- البحث حسب الاسم الأول -->
            <div class="grid-item input-container">
                <input type="text" id="firstname" name="firstname" placeholder="ادخل الاسم الأول" value="{{ request.GET.firstname }}">
            </div>
            <!-- البحث حسب الاسم الثاني -->
            <div class="grid-item input-container">
                <input type="text" id="secondname" name="secondname" placeholder="ادخل الاسم الثاني" value="{{ request.GET.secondname }}">
            </div>
            <!-- البحث حسب الاسم الثالث -->
            <div class="grid-item input-container">
                <input type="text" id="thirdname" name="thirdname" placeholder="ادخل الاسم الثالث" value="{{ request.GET.thirdname }}">
            </div>
            <!-- التصفية حسب البيانات الأساسية -->
            <div class="grid-item input-container">
                <select name="has_basicinfo">
                    <option value="">لديه بيانات أساسية</option>
                    <option value="yes" {% if request.GET.has_basicinfo == "yes" %}selected{% endif %}>نعم</option>
                    <option value="no" {% if request.GET.has_basicinfo == "no" %}selected{% endif %}>لا</option>
                </select>
            </div>
            <!-- التصفية حسب الجنس -->
            <div class="grid-item input-container">
                <select name="gender">
                    <option value="">اختر الجنس</option>
                    <option value="M" {% if request.GET.gender == "M" %}selected{% endif %}>ذكر</option>
                    <option value="F" {% if request.GET.gender == "F" %}selected{% endif %}>أنثى</option>
                </select>
            </div>
            <!-- التصفية حسب رقم الهاتف -->
           
            <!-- التصفية حسب الدائرة -->
            <div class="grid-item input-container">
                <select name="office">
                    <option value="">اختر الدائرة</option>
                    {% for office in offices %}
                        <option value="{{ office.id }}" {% if request.GET.office == office.id|stringformat:"d" %}selected{% endif %}>
                            {{ office.name }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <!-- زر البحث -->
            <div class="grid-item input-container">
                <button type="submit">بحث</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

{% block titleleftsidemenu %}
{% endblock %}

{% block leftsidemenu %}
<label class="result-label">عدد نتائج البحث : {{ employee_count }}</label>
{% endblock %}

{% block titlecontent %}
{% endblock %}

{% block content %}
<table>
    <thead>
        <tr>
            <th>الرقم الوظيفي</th>
            <th>الاسم الكامل</th>
            <th>رقم الهاتف</th>
            <th>ايقاف الحساب </th>
            <th>تغير الباسورد  </th>
            <th>لوحة تحكم الموظف</th>
        </tr>
    </thead>
    <tbody>
        {% for employee in employees %}
        <tr>
            <td>{{ employee.username }}</td>
            <td>
                {% if employee.basic_info %}
                    {{ employee.basic_info.get_full_name }} - 
                    {% if perms.personalinfo.can_create_official_documents %}
                    <a href="{% url 'personalinfo:add_official_document' employee.basic_info.slug %}">اضافة وثيقة  </a>
                    {% endif %}

                {% else %}
                    لا توجد معلومات 
                    {% if perms.personalinfo.can_add_employee_basic_info %}
                     - 
                    <a href="{% url 'personalinfo:addbasicinfo' employee.slug %}">إضافة معلومات أساسية</a>
                    {% else%}
                    ليس لديك صلاحية الاضافة
                    {% endif %}
                {% endif %}
            </td>
            <td>
                {% if employee.basic_info and employee.basic_info.phone_number %}
                    {{ employee.basic_info.phone_number }}
                {% else %}
                    لا يوجد
                {% endif %}
            </td>
            <td>
                <a href="{% url 'accounts:toggle_employee_status' employee.id %}">ايقاف الحساب  </a>
            </td>
            <td>
                <a href="{% url 'accounts:change_employee_password' employee.id %}">تغير    </a>
            </td>
            <td>
                <a href="{% url 'accounts:employeedashboard' employee.slug %}">عرض لوحة التحكم</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">لا توجد بيانات لعرضها.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block pagination %}
<div class="pagination-container">
    <div class="pagination-info">
        <span>عدد العناصر بالصفحة:</span>
        <form method="get" action="" class="pagination-form">
            <input type="number" id="results_per_page" name="results_per_page" placeholder="عدد النتائج لكل صفحة" value="{{ request.GET.results_per_page|default:10 }}" class="pagination-input">
        </form>
    </div>
    <div class="pagination-controls">
        {% if employees.has_previous %}
            <a href="?{{ request.GET.urlencode }}&page=1" class="pagination-button">الأولى</a>
            <a href="?{{ request.GET.urlencode }}&page={{ employees.previous_page_number }}" class="pagination-button">السابق</a>
        {% endif %}
        <span>صفحة {{ employees.number }} من {{ employees.paginator.num_pages }}</span>
        {% if employees.has_next %}
            <a href="?{{ request.GET.urlencode }}&page={{ employees.next_page_number }}" class="pagination-button">التالي</a>
            <a href="?{{ request.GET.urlencode }}&page={{ employees.paginator.num_pages }}" class="pagination-button">الأخيرة</a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block titlesidemenu %}
{% endblock %}



{% block sidemenu %}



<div class="button-container">
    <a href="{% url 'accounts:view_profile' %}" class="custom-button">  الصفحة الشخصية    </a>
    

    

</div>



{% endblock %}

accounts/templates/accounts/accountsaffairs/accounts_main_page.html
{% extends 'core/base.html' %}

{% block titlesidemenu %} <h2>{{ basic_info.get_full_name }} </h2> 





{% endblock %}


{% block titlecontent %} 


 
{% endblock %} 


{% block sidemenu %}

 <a href="{% url 'accounts:view_profile'  %}"> الملف الشخصي  </a> 
<br>
{% endblock %}



{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<main>

    <section class="dashboard-cards">
        {% if user.is_superuser %} 
    <div class="container">
        <div class="card blue">
            <h3><a href="{% url 'accounts:employee_list' %}"> عرض الموظفين</a></h3> 
            <p> هنا يتم عرض جميع الموظفين المسجلين بالنظام</p>
        </div>
    </div>

    {% endif %}  
    
    {% if user.is_superuser %} 
        <div class="container">
            <div class="card blue">
                {% comment %} <h3><a href="{% url 'accounts:login_activities_list' %}"> عرض جميع الانشطة</a></h3>  {% endcomment %}
                <p> هنا يتم عرض جميع انشطة الدخول والخروج للموظفين المسجلين بالنظام</p>
            </div>
        </div>
        {% endif %}  


        {% if user.is_superuser %} 
    
        <div class="container">
            <div class="card blue">
                {% comment %} <h3><a href="{% url 'accounts:register_new_employee' %}"> انشاء حسابات جديدة   </a></h3>  {% endcomment %}
                <p> هنا يتم انشاء حسابات (تسجيل موظفين) </p>
            </div>
        </div>
        {% endif %}  

        {% if user.is_superuser %} 
        <div class="container">
            <div class="card blue">
                {% comment %} <h3><a href="{% url 'accounts:assign_permissions' %}">   ادارة الصلاحيات والاذونات   </a></h3>  {% endcomment %}
                <p> هنا يتم انشاء حسابات (تسجيل موظفين) </p>
            </div>
        </div>

        {% endif %}  

        {% if user.is_superuser %} 
        <div class="container">
            <div class="card blue">
                <h3> <a href="{% url 'accounts:employee_search_view' %}">    البحث عن موظف  </a></h3> 
                <p> هنا يتم البحث عن موظف  </p>
            </div>
        </div>

        {% endif %}  

    

    
        
   
    <br>


    
    
    </section>
    
</main> 



{% endblock %}

accounts/templates/accounts/accountsaffairs/approve_employee.html
{% extends 'core/base.html' %}

{% block sidemenu %}

{% endblock %}

{% block content %}
  <h1>موافقة الموظف: {{ employee.username }}</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">حفظ التعديلات</button>
  </form>
  
  {% comment %} <a href="{% url 'employee_list' %}">العودة إلى قائمة الموظفين</a> {% endcomment %}
{% endblock %}

accounts/templates/accounts/accountsaffairs/employee_all_activity.html
{% extends 'core/base.html' %}



{% block content %}
<h1 class="section-header">أنشطة الموظف: {{ employee.basic_info.get_full_name }}</h1>

{% if activity_logs %}
<table class="custom-table">
    <thead>
        <tr>
            <th>الحدث</th>
            <th>التاريخ</th>
            
            <th>المتصفح</th>
            <th>نظام التشغيل</th>
            <th>الجهاز</th>
        </tr>
    </thead>
    <tbody>
        {% for log in activity_logs %}
        <tr>
            <td>{{ log.action }}</td>
            <td>{{ log.timestamp }}</td>
           
            <td>{{ log.browser }}</td>
            <td>{{ log.operating_system }}</td>
            <td>{{ log.device }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
    <div class="alert alert-error">
        لا توجد أنشطة للعرض.
    </div>
{% endif %}
{% endblock %}



{% block sidemenu %}



<div class="button-container">
    <a href="{% url 'accounts:view_profile' %}" class="custom-button">  الصفحة الشخصية    </a>
   

    

</div>



{% endblock %}

{% block leftsidemenu %}
<label class="result-label">   {{ request.user }}</label>
{% endblock %}

accounts/templates/accounts/accountsaffairs/emplpoyee_change_password.html
{% extends 'core/base.html' %}

{% block title %}قائمة الموظفين{% endblock %}

{% block content %}

<!-- change_password.html -->

<form method="POST">
    {% csrf_token %}
    <label for="new_password">كلمة المرور الجديدة</label>
    <input type="password" id="new_password" name="new_password" required>
    <button type="submit" class="update_button"
    >تغيير كلمة المرور</button>
</form>


{% endblock %}

{% block leftsidemenu %}
<label class="result-label">   {{ request.user }}</label>
{% endblock %}


{% block sidemenu %}



<div class="button-container">
    <a href="{% url 'accounts:view_profile' %}" class="custom-button">  الصفحة الشخصية    </a>
    

    

</div>



{% endblock %}