MOY/urls.py
from django.contrib import admin  # استيراد وحدة إدارة الموقع من Django
from django.urls import path, include  # استيراد الدوال المسؤولة عن تعريف المسارات وربطها
from django.conf import settings  # استيراد إعدادات المشروع
from django.conf.urls.static import static  # استيراد الدالة المسؤولة عن إعداد المسارات للملفات الثابتة والإعلامية أثناء التطوير

#from django.conf.urls.i18n import urlpatterns as i18n_urlpatterns



from django.conf.urls import handler403
from core.views import custom_403  # استدعاء الدالة من تطبيق core

handler403 = 'core.views.custom_403'


urlpatterns = [
    path('admin/', admin.site.urls), # رابط لوحة التحكم
    path('', include('core.urls')), # رابط التطبيق

    
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
   
    path('personalinfo/', include('personalinfo.urls')),
    path('hrhub/', include('hrhub.urls')),
    path('rddepartment/', include('rddepartment.urls')),



    # # path('financialaffairs/', include('financialaffairs.urls')),
    
    path('locations/', include('locations.urls')),
    path('requests_app/', include('requests_app.urls')),
     
  
]


if settings.DEBUG:  # أثناء التطوير
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
   
    pass

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import employeedashboard
from . import permissions
from . import registration
from . import profile
from . import views
from . import accountsaffairs
from .logs import personalinfo
from . import search
from .logs import rdd
from .logs import accounts
from . import employeesearch
from . import employeeactivitylog

app_name = 'accounts'


urlpatterns = [

    ################ Control Panel #################
     path('main_control_panel/', views.main_control_panel, name='main_control_panel'),

    path('main_accounts_page/', views.main_accounts_page, name='main_accounts_page'),


     path('mainemployeesearch/', employeesearch.mainemployeesearch, name='mainemployeesearch'),


    # رابط عرض تفاصيل الموظف
    path('employeedashboard/<slug:slug>/', employeedashboard.employeedashboard, name='employeedashboard'),
    path('searchemployeedashboard/<slug:slug>/', employeedashboard.searchemployeedashboard, name='searchemployeedashboard'),



    ################ Permissions #################
    path('mainlistpermissions/', permissions.mainlistpermissions, name='mainlistpermissions'),
    path('list_permissions/', permissions.list_model_permissions, name='list_permissions'),
    path('employees/<int:employee_id>/assign-permissions/', permissions.assign_permissions, name='assign_permissions'),
    path('employees/assign_bulk_permissions/', permissions.assign_bulk_permissions, name='assign_bulk_permissions'),
    path('employees/revoke_bulk_permissions/', permissions.revoke_bulk_permissions, name='revoke_bulk_permissions'),

    #################################### Registration ##############################################
     path('register_new_employee/', registration.register_new_employee, name='register_new_employee'),
     path('generate_sample_upload_employees_csv_csv/', registration.generate_sample_upload_employees_csv_csv, name='generate_sample_upload_employees_csv_csv'),
     path('upload_employees_csv/', registration.upload_employees_csv, name='upload_employees_csv'),
     path('login_view/', registration.login_view, name='login_view'),
    path('password_change/', registration.CustomPasswordChangeView.as_view(), name='password_change'),
    path('logout/', registration.logout_view, name='logout'),



    ################################### Profile #######################
    path('profile/', profile.view_profile, name='view_profile'),



     ### accountsaffairs

path('accounts_main_affiars/', accountsaffairs.accounts_main_affiars, name='accounts_main_affiars'),

    path('employee_list/', accountsaffairs.employee_list, name='employee_list'),
        path('toggle_status/<int:employee_id>/', accountsaffairs.toggle_employee_status, name='toggle_employee_status'),

    path('employee/<str:username>/login-activities/', accountsaffairs.employee_login_activity, name='employee_login_activity'),
#     path('login_activities_list/', accountsaffairs.login_activity_list, name='login_activities_list'),
    path('employee/<slug:slug>/approve/', accountsaffairs.approve_employee, name='approve_employee'),
     
     path('employee_employee_view/', accountsaffairs.employee_employee_view, name='employee_employee_view'),
    path('change-password/<int:employee_id>/', accountsaffairs.change_employee_password, name='change_employee_password'),
    path('export_filtered_employee_csv/', accountsaffairs.export_filtered_employee_csv, name='export_filtered_employee_csv'),



    
        
    path('basic_info_change_log/', personalinfo.basic_info_change_log, name='basic_info_change_log'),
     path('officialtypeslogs/', personalinfo.officialtypeslogs, name='officialtypeslogs'),
    path('emploeeofficialdoc/', personalinfo.emploeeofficialdoc, name='emploeeofficialdoc'),
    path('religionchangelog/', personalinfo.religionchangelog, name='religionchangelog'),
    path('nationalismchangelog/', personalinfo.nationalismchangelog, name='nationalismchangelog'),
    path('additionalinfochangelog/', personalinfo.additionalinfochangelog, name='additionalinfochangelog'),

    path('educationdegreetypechangelog/', rdd.educationdegreetypechangelog, name='educationdegreetypechangelog'),
    path('collegechangelog/', rdd.collegechangelog, name='collegechangelog'),
    path('foreignuniversitychangelog/', rdd.foreignuniversitychangelog, name='foreignuniversitychangelog'),
        path('employeeeducationchangelog/', rdd.employeeeducationchangelog, name='employeeeducationchangelog'),
        
    # path('employeechangelog/', accounts.employeechangelog, name='employeechangelog'),

    




    ############################# Search #######
     path('mainemplpyeesearch/', search.mainemplpyeesearch, name='mainemplpyeesearch'),


     ########################## Resset Password ##################
#       path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset_by_employee_id'),
#     path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
# path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
#         template_name='registration/password_reset_confirm.html'
#     ), name='password_reset_confirm'),    
#     path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('employee_activity_view/', employeeactivitylog.employee_activity_view, name='employee_activity_view'),
    path('employee_activity/<slug:slug>/activity/', employeeactivitylog.employee_activity, name='employee_activity'),
    path('make_superuser/<int:employee_id>/', permissions.make_superuser, name='make_superuser'),

]

rddepartment/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth import views as auth_views

from . import views
from . import foreignuniversity
from . import  college
from . import iraqiuniversity
from . import  employeeeducation
from . import coursecertificatetype
from . import educationdegreetype
from . import employeecoursecertificate


app_name = 'rddepartment'



urlpatterns = [

    # #### views
    path('main_rddepartment/', views.main_rddepartment, name='main_rddepartment'),
    



    # # #### main_Education_Degree_Type
    path('main_education_degree_type/', educationdegreetype.main_education_degree_type, name='main_education_degree_type'),
    path('add_education_degree_type/', educationdegreetype.add_education_degree_type, name='add_education_degree_type'),
    path('education_degree_type_detail/<slug:slug>/', educationdegreetype.education_degree_type_detail, name='education_degree_type_detail'),
    path('update_education_degree_type/<slug:slug>/', educationdegreetype.update_education_degree_type, name='update_education_degree_type'),
    path('delete_education_degree_type/<slug:slug>/', educationdegreetype.delete_education_degree_type, name='delete_education_degree_type'),
     path('export_education_degree_type_to_csv/', educationdegreetype.export_education_degree_type_to_csv, name='export_education_degree_type_to_csv'),


     # ################## college ##################

    path('main_college/', college.main_college, name='main_college'),
    path('add_college/', college.add_college, name='add_college'),
    path('college_detail/<slug:slug>/', college.college_detail, name='college_detail'),
    path('update_college/<slug:slug>/', college.update_college, name='update_college'),
    path('delete_college/<slug:slug>/', college.delete_college, name='delete_college'),
    path('export_college_to_csv/', college.export_college_to_csv, name='export_college_to_csv'),



    ############# Foreignuniversity.py
    path('main_foreignuniversity/', foreignuniversity.main_foreignuniversity, name='main_foreignuniversity'),
    path('add_foreignuniversity/', foreignuniversity.add_foreignuniversity, name='add_foreignuniversity'),
    path('get_countries_by_continent/', foreignuniversity.get_countries_by_continent, name='get_countries_by_continent'),
    path('foreignuniversitys_detail/<slug:slug>/', foreignuniversity.foreignuniversitys_detail, name='foreignuniversitys_detail'),
    path('update_foreignuniversitys/<slug:slug>/', foreignuniversity.update_foreignuniversitys, name='update_foreignuniversitys'),
    path('delete_foreignuniversity/<slug:slug>/', foreignuniversity.delete_foreignuniversity, name='delete_foreignuniversity'),
    path('download_sample_foreign_universities_csv', foreignuniversity.download_sample_foreign_universities_csv, name='download_sample_foreign_universities_csv'),
    path('upload_foreign_university_csv', foreignuniversity.upload_foreign_university_csv, name='upload_foreign_university_csv'),

    # path('get_countries_by_continent/<int:continent_id>/', foreignuniversity.get_countries_by_continent, name='get_countries_by_continent'),




   

    # ################### Iraqiuniversity ##################
    path('main_iraqiuniversity/', iraqiuniversity.main_iraqiuniversity, name='main_iraqiuniversity'),
    path('add_iraqiuniversity/', iraqiuniversity.add_iraqiuniversity, name='add_iraqiuniversity'),
    path('upload_iraqi_university_csv/', iraqiuniversity.upload_iraqi_university_csv, name='upload_iraqi_university_csv'),
    path('download_sample_iraqi_university_csv/', iraqiuniversity.download_sample_iraqi_university_csv, name='download_sample_iraqi_university_csv'),
    path('iraqiuniversity_detail/<slug:slug>/', iraqiuniversity.iraqiuniversity_detail, name='iraqiuniversity_detail'),
    path('update_iraqiuniversity/<slug:slug>/', iraqiuniversity.update_iraqiuniversity, name='update_iraqiuniversity'),
    path('delete_iraqiuniversity/<slug:slug>/', iraqiuniversity.delete_iraqiuniversity, name='delete_iraqiuniversity'),
     path('export_iraqi_university_to_csv/', iraqiuniversity.export_iraqi_university_to_csv, name='export_iraqi_university_to_csv'),
    




    # ###############     employeeeducation
    path('main_employeeeducation/', employeeeducation.main_employeeeducation, name='main_employeeeducation'),
    path('add_employeeeducation/<slug:slug>/', employeeeducation.add_employeeeducation, name='add_employeeeducation'),
    path('employeeeducation_detail/<slug:slug>/', employeeeducation.employeeeducation_detail, name='employeeeducation_detail'),
    path('employeeeducation_detail_employee/<slug:slug>/', employeeeducation.employeeeducation_detail_employee, name='employeeeducation_detail_employee'),

    

    
    path('employee_cer_education_detail/<slug:slug>/', employeeeducation.employee_cer_education_detail, name='employee_cer_education_detail'),
    path('update_employeeeducation/<slug:slug>/', employeeeducation.update_employeeeducation, name='update_employeeeducation'),
    path('delete_employee_education/<slug:slug>/', employeeeducation.delete_employee_education, name='delete_employee_education'),

    path('download_employee_education_sample_csv/', employeeeducation.download_employee_education_sample_csv, name='download_employee_education_sample_csv'),
    path('upload_employee_education_csv/', employeeeducation.upload_employee_education_csv, name='upload_employee_education_csv'),
    path('export_filtered_employee_education_csv/', employeeeducation.export_filtered_employee_certificates_csv, name='export_filtered_employee_education_csv'),
    # path('employeeeducation_employee_detail/<slug:employee_slug>/', employeeeducation.employeeeducation_employee_detail, name='employee_education_detail'),
    # path('export_employeeeducation_csv/', employeeeducation.export_employeeeducation_csv, name='export_employeeeducation_csv'),
    # path('employeeeducationstatistics/', employeeeducation.employeeeducationstatistics, name='employeeeducationstatistics'),
    # path('employee_certificates_view/<slug:slug>/certificates/', employeeeducation.employee_certificates_view, name='employee_certificates_view'),



    # ################### coursecertificatetype
    path('main_coursecertificatetype/', coursecertificatetype.main_coursecertificatetype, name='main_coursecertificatetype'),
    path('add_coursecertificatetype/', coursecertificatetype.add_coursecertificatetype, name='add_coursecertificatetype'),
    path('coursecertificatetype_detail/<slug:slug>/', coursecertificatetype.coursecertificatetype_detail, name='coursecertificatetype_detail'),
    path('update_coursecertificatetype/<slug:slug>/', coursecertificatetype.update_coursecertificatetype, name='update_coursecertificatetype'),
    path('delete_coursecertificatetype/<slug:slug>/', coursecertificatetype.delete_coursecertificatetype, name='delete_coursecertificatetype'),

    # #####
    path('main_coursecertificateinstitutions/', coursecertificatetype.main_coursecertificateinstitutions, name='main_coursecertificateinstitutions'),
    path('add_coursecertificateinstitutions/', coursecertificatetype.add_coursecertificateinstitutions, name='add_coursecertificateinstitutions'),
    path('coursecertificateinstitution_detail/<slug:slug>/', coursecertificatetype.coursecertificateinstitution_detail, name='coursecertificateinstitution_detail'),
    path('update_coursecertificateinstitution/<slug:slug>/', coursecertificatetype.update_coursecertificateinstitution, name='update_coursecertificateinstitution'),
    path('delete_coursecertificateinstitution/<slug:slug>/', coursecertificatetype.delete_coursecertificateinstitution, name='delete_coursecertificateinstitution'),
    # #####

      path('mainemployeecoursecertificate/', employeecoursecertificate.mainemployeecoursecertificate, name='mainemployeecoursecertificate'),
      path('add_employeecoursecertificate/<slug:slug>/', employeecoursecertificate.add_employeecoursecertificate, name='add_employeecoursecertificate'),
      path('all_employee_certificates/<slug:slug>/', employeecoursecertificate.all_employee_certificates, name='all_employee_certificates'),
      path('all_employee_certificates_employee/<slug:slug>/', employeecoursecertificate.all_employee_certificates_employee, name='all_employee_certificates_employee'),
      path('download_sample_employee_course_certificate_csv/', employeecoursecertificate.download_sample_employee_course_certificate_csv, name='download_sample_employee_course_certificate_csv'),
      path('upload_employee_course_certificate_csv/', employeecoursecertificate.upload_employee_course_certificate_csv, name='upload_employee_course_certificate_csv'),
      path('export_filtered_employee_certificates_csv/', employeecoursecertificate.export_filtered_employee_certificates_csv, name='export_filtered_employee_certificates_csv'),





      
     path('update_employeecoursecertificate/<slug:slug>/', employeecoursecertificate.update_employeecoursecertificate, name='update_employeecoursecertificate'),
     path('delete_employeecoursecertificate/<slug:slug>/', employeecoursecertificate.delete_employeecoursecertificate, name='delete_employeecoursecertificate'),
#      path('download_sample_employee_course_certificate_csv/', coursecertificatetype.download_sample_employee_course_certificate_csv, name='download_sample_employee_course_certificate_csv'),
#      path('upload_employee_course_certificate_csv/', coursecertificatetype.upload_employee_course_certificate_csv, name='upload_employee_course_certificate_csv'),
# path('employee/<slug:slug>/course-certificates/', coursecertificatetype.employee_course_certificates, name='employee_course_certificates'),





   
    
]

rddepartment/models.py
from django.db import models

# Create your models here.

rddepartment/forms/EducationDegreeTypeForm.py
from django import forms
from rddepartment.models.Education_Degree_Type import EducationDegreeType

class EducationDegreeTypeForm(forms.ModelForm):
    class Meta:
        model = EducationDegreeType
        fields = [
            'name_in_arabic', 
            'name_in_english', 
            'grade_number', 
            'step_number', 
            'education_degree_number', 
            'years_effects', 
            'stop_point', 
            'has_effect', 
            'addtion_years_effects', 
            'comments'
        ]
        widgets = {
            'comments': forms.Textarea(attrs={'rows': 3}),
        }

rddepartment/templates/rddepartment/employeeeducation/employee_certificates.html
{% extends 'core/base.html' %}


{% block searchbar %}

    
{% endblock %}

{% block titleleftsidemenu %}


{% endblock %}

{% block leftsidemenu %}

{% endblock %}


{% block titlecontent %}

{% endblock %}


{% block content %}

<h1>الشهادات الأكاديمية للموظف: {{ basic_info.get_full_name }}</h1>

    <h2>الشهادات الحاصل عليها:</h2>
    <table class="custom-table">
        <thead>
            <tr>
                <th>#</th>
                <th>نوع الشهادة</th>
                <th>الكلية</th>
                <th>اسم المؤسسة</th>
                <th>تاريخ الإصدار</th>
              
            </tr>
        </thead>
        <tbody>
            {% for certificate in certificates %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ certificate.education_degree_type }}</td>
                    <td>{{ certificate.college }}</td>
                    <td>{{ certificate.institution_name }}</td>
                    <td>{{ certificate.date_issued }}</td>
                    
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6">لا توجد شهادات مسجلة لهذا الموظف.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}



{% block titlesidemenu %}

{% endblock %}

{% block sidemenu %}



<div class="button-container">
    <a href="{% url 'accounts:view_profile' %}" class="custom-button">  الصفحة الشخصية    </a>
    <a href="{% url 'accounts:main_control_panel' %}" class="custom-button">  لوحة التحكم     </a>
    <a href="{% url 'rddepartment:main_rddepartment' %}" class="custom-button">   الشهادات والتطوير     </a>
    <a href="{% url 'rddepartment:main_employeeeducation' %}" class="custom-button">   شهادات الموظفين      </a>
    <a href="{% url 'rddepartment:download_employee_education_sample_csv' %}" class="custom-button">   نموذج CSV      </a>

    {% if perms.personalinfo.can_add_employee_education %} 
    <a href="{% url 'rddepartment:upload_employee_education_csv' %}" class="custom-button">   رفع CSV      </a>
    {% else %}
    ليس لديك صلاحية الرفع
    {% endif %}
    
    
</div>



{% endblock %}

rddepartment/templates/rddepartment/employeeeducation/main_employeeeducation.html
{% extends 'core/base.html' %}


{% block searchbar %}

<form method="get" action=""><div class="main_searchbar">

    <div class="grid-container">
        <div class="grid-item input-container">
            <input type="text" id="username" name="username" placeholder="ادخل الرقم الوظيفي" value="{{ request.GET.username }}">
        </div>
        <div class="grid-item input-container">
            <input type="text" id="firstname" name="firstname" placeholder="ادخل الاسم الأول" value="{{ request.GET.firstname }}">
        </div>
        <div class="grid-item input-container">
            <input type="text" id="secondname" name="secondname" placeholder="ادخل الاسم الثاني" value="{{ request.GET.secondname }}">
        </div>
        <div class="grid-item input-container">
            <input type="text" id="thirdname" name="thirdname" placeholder="ادخل الاسم الثالث" value="{{ request.GET.thirdname }}">
        </div>
        <div class="grid-item input-container">
            <select name="has_certificate">
                <option value="">لديه شهادة</option>
                <option value="yes" {% if request.GET.has_certificate == "yes" %}selected{% endif %}>نعم</option>
                <option value="no" {% if request.GET.has_certificate == "no" %}selected{% endif %}>لا</option>
            </select>
        </div>

        <div class="grid-item input-container">
            <select name="gender">
                <option value="">اختر الجنس</option>
                <option value="M" {% if request.GET.gender == "M" %}selected{% endif %}>ذكر</option>
                <option value="F" {% if request.GET.gender == "F" %}selected{% endif %}>أنثى</option>
            </select>
        </div>
        
        
       
        <div class="grid-item input-container">
            <select name="has_phone">
                <option value="">لديه رقم هاتف</option>
                <option value="yes" {% if request.GET.has_phone == "yes" %}selected{% endif %}>نعم</option>
                <option value="no" {% if request.GET.has_phone == "no" %}selected{% endif %}>لا</option>
            </select>
        </div>
        
            <div class="grid-item input-container">
                <button type="submit">بحث</button>
            </div>
           
    </div>
</div>
</form>


{% endblock %}

{% block titleleftsidemenu %}


{% endblock %}
{% block leftsidemenu %}
<label class="result-label">عدد نتائج البحث : {{ employee_count }}</label>

<div class="search-container">
    <form method="get" action="">
        <div class="grid-item input-container">
            <select name="office">
                <option value="">اختر الدائرة</option>
                {% for office in offices %}
                    <option value="{{ office.id }}" {% if request.GET.office == office.id|stringformat:"d" %}selected{% endif %}>
                        {{ office.name }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="grid-item input-container">
            <select name="certificate_type">
                <option value="">اختر نوع الشهادة</option>
                {% for degree_type in education_degree_types %}
                    <option value="{{ degree_type.id }}" {% if request.GET.certificate_type == degree_type.id|stringformat:"s" %}selected{% endif %}>
                        {{ degree_type.name_in_arabic }}
                    </option>
                {% endfor %}
            </select>
        </div>
    
        <div class="grid-item input-container">
            <select name="college">
                <option value="">اختر الكلية</option>
                {% for college in colleges %}
                    <option value="{{ college.id }}" {% if request.GET.college == college.id|stringformat:"s" %}selected{% endif %}>
                        {{ college.name_in_arabic }}
                    </option>
                {% endfor %}
            </select>
        </div>

       
        <div class="grid-item input-container">
            <select name="has_iraqi_university">
                <option value="">خريج جامعة عراقية</option>
                <option value="yes" {% if request.GET.has_iraqi_university == "yes" %}selected{% endif %}>نعم</option>
                <option value="no" {% if request.GET.has_iraqi_university == "no" %}selected{% endif %}>لا</option>
            </select>
        </div>

        <div class="grid-item input-container">
            <select name="has_foreign_university">
                <option value="">خريج جامعة اجنبية  </option>
                <option value="yes" {% if request.GET.has_foreign_university == "yes" %}selected{% endif %}>نعم</option>
                <option value="no" {% if request.GET.has_foreign_university == "no" %}selected{% endif %}>لا</option>
            </select>
        </div>

        <div class="grid-item input-container">
            <select name="has_addition_certificate">
                <option value="">لديه شهادة مضافة</option>
                <option value="yes" {% if request.GET.has_addition_certificate == "yes" %}selected{% endif %}>نعم</option>
                <option value="no" {% if request.GET.has_addition_certificate == "no" %}selected{% endif %}>لا</option>
            </select>
        </div>

        <br>
        <button type="submit" class="leftsidemenu-button">بحث</button>
    </form>
</div>
{% endblock %}


{% block titlecontent %}

{% endblock %}


{% block content %}
<table>
    <thead>
        <tr>
            <th>الرقم الوظيفي </th>
            <th>الاسم الكامل</th>
            <th>رقم الهاتف  </th>
            <th>لديه شهادة</th> <!-- العمود الجديد -->
            <th>لوحة تحكم الموظف </th>
          
        </tr>
    </thead>
    <tbody>
        {% for employee in employees %}
        <tr>
            <td>{{ employee.username }}</td>
            <td>
                {% if employee.basic_info %}
                {{ employee.basic_info.get_full_name }}
                {% if perms.personalinfo.can_add_employee_education %} -
                
                <a href="{% url 'rddepartment:add_employeeeducation' employee.basic_info.slug %}">اضافة شهادة  </a>
               
                {% endif %}
            {% else %}
            لا توجد معلومات - 
            {% endif %}
            </td>
            <td>
                {% if employee.basic_info and employee.basic_info.phone_number %}
                    {{ employee.basic_info.phone_number }}
                {% else %}
                    لا يوجد
                {% endif %}
            </td>
            <td>
                {% if employee.basic_info %}
                {% if employee.basic_info.employee_education.exists %}
                     نعم -  <a href="{% url 'rddepartment:employeeeducation_detail' employee.basic_info.slug %}">عرض  </a>
                {% else %}
                    لا
                {% endif %}

                {% else %}
               
                {% endif %}
            </td>
            
            
            <td>
                {% if perms.personalinfo.can_access_employee_dashboard %}
                <a href="{% url 'accounts:employeedashboard' employee.slug %}">عرض لوحة التحكم</a>
                {% else%}
                ليس لديك صلاحية الوصول
                {% endif %}
            </td>
         
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">لا توجد بيانات لعرضها.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block pagination %}
<div class="pagination-container">
    <div class="pagination-info">
        <span>عدد العناصر بالصفحة:</span>
        <form method="get" action="" class="pagination-form">
            <input type="number" id="results_per_page" name="results_per_page" placeholder="عدد النتائج لكل صفحة" value="{{ request.GET.results_per_page|default:10 }}" class="pagination-input">
        </form>
    </div>
    <div class="pagination-controls">
        {% if employees.has_previous %}
            <a href="?{{ request.GET.urlencode }}&page=1" class="pagination-button">الأولى</a>
            <a href="?{{ request.GET.urlencode }}&page={{ employees.previous_page_number }}" class="pagination-button">السابق</a>
        {% endif %}
        <span>صفحة {{ employees.number }} من {{ employees.paginator.num_pages }}</span>
        {% if employees.has_next %}
            <a href="?{{ request.GET.urlencode }}&page={{ employees.next_page_number }}" class="pagination-button">التالي</a>
            <a href="?{{ request.GET.urlencode }}&page={{ employees.paginator.num_pages }}" class="pagination-button">الأخيرة</a>
        {% endif %}
    </div>
</div>
{% endblock %}




{% block titlesidemenu %}

{% endblock %}



{% block sidemenu %}



<div class="button-container">
    <a href="{% url 'accounts:view_profile' %}" class="custom-button">  الصفحة الشخصية    </a>
    <a href="{% url 'accounts:main_control_panel' %}" class="custom-button">  لوحة التحكم     </a>
    <a href="{% url 'rddepartment:main_rddepartment' %}" class="custom-button">   الشهادات والتطوير     </a>
    <a href="{% url 'rddepartment:download_employee_education_sample_csv' %}" class="custom-button">   نموذج CSV      </a>

    {% if perms.personalinfo.can_add_employee_education %} 
    <a href="{% url 'rddepartment:upload_employee_education_csv' %}" class="custom-button">   رفع CSV      </a>
    {% else %}
    ليس لديك صلاحية الرفع
    {% endif %}
    
    <a href="{% url 'rddepartment:export_filtered_employee_education_csv' %}?{{ request.GET.urlencode }}" class="custom-button">تصدير النتائج</a>

</div>



{% endblock %}