MOY/urls.py
from django.contrib import admin  # استيراد وحدة إدارة الموقع من Django
from django.urls import path, include  # استيراد الدوال المسؤولة عن تعريف المسارات وربطها
from django.conf import settings  # استيراد إعدادات المشروع
from django.conf.urls.static import static  # استيراد الدالة المسؤولة عن إعداد المسارات للملفات الثابتة والإعلامية أثناء التطوير

#from django.conf.urls.i18n import urlpatterns as i18n_urlpatterns



from django.conf.urls import handler403
from core.views import custom_403  # استدعاء الدالة من تطبيق core

handler403 = 'core.views.custom_403'


urlpatterns = [
    path('admin/', admin.site.urls), # رابط لوحة التحكم
    path('', include('core.urls')), # رابط التطبيق

    
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
   
    path('personalinfo/', include('personalinfo.urls')),
    path('hrhub/', include('hrhub.urls')),
    path('rddepartment/', include('rddepartment.urls')),



    # # path('financialaffairs/', include('financialaffairs.urls')),
    
    path('locations/', include('locations.urls')),
    path('requests_app/', include('requests_app.urls')),
     
  
]


if settings.DEBUG:  # أثناء التطوير
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
   
    pass

locations/urls.py
from django.urls import path

from . import views
from . import governorate
from . import region
from . import continent
from . import country



app_name = 'locations' 

urlpatterns = [
    
    #### Views 
    path('main_locations_dashboard/', views.main_locations_dashboard, name='main_locations_dashboard'),

    #### Governorate
    path('governorate_create/', governorate.create_governorate, name='governorate_create'),
    path('governorate_statistics/', governorate.governorate_statistics, name='governorate_statistics'),
    path('export_governorates_csv/', governorate.export_governorates_csv, name='export_governorates_csv'),
    path('governorates/<slug:slug>/', governorate.governorate_detail, name='governorate_detail'),
    path('governorates/<slug:slug>/update/', governorate.update_governorate, name='update_governorate'),
    path('governorates/<slug:slug>/delete/', governorate.delete_governorate, name='delete_governorate'),
    path('download_sample_governorates_csv/', governorate.download_sample_governorates_csv, name='download_sample_governorates_csv'),
    path('upload_governorates_csv/', governorate.upload_governorates_csv, name='upload_governorates_csv'),
    path('download_all_governorates_csv/', governorate.download_all_governorates_csv, name='download_all_governorates_csv'),



    
    #### Region

   path('create_region/', region.create_region, name='create_region'),
   path('region_statistics/', region.region_statistics, name='region_statistics'),
   path('export_regions_csv/', region.export_regions_csv, name='export_regions_csv'),
    path('regions/<slug:slug>/', region.region_detail, name='region_detail'),

    path('regions/<slug:slug>/update/', region.update_region, name='update_region'),

    path('regions/<slug:slug>/delete/', region.delete_region, name='delete_region'),
     path('download_sample_regions_csv/', region.download_sample_regions_csv, name='download_sample_regions_csv'),
    path('upload_regions_csv/', region.upload_regions_csv, name='upload_regions_csv'),
    path('export_all_regions_csv/', region.export_all_regions_csv, name='export_all_regions_csv'),



   ##### Continent
   path('create_continent/', continent.create_continent, name='create_continent'),
   path('continent_statistics/', continent.continent_statistics, name='continent_statistics'),
   path('export_continents_csv/', continent.export_continents_csv, name='export_continents_csv'),
  path('continents/<slug:slug>/', continent.continent_detail, name='continent_detail'),
  path('continents/<slug:slug>/update/', continent.update_continent, name='update_continent'),
  path('continents/<slug:slug>/delete/', continent.delete_continent, name='delete_continent'),
     path('export_all_continents_csv/', continent.export_all_continents_csv, name='export_all_continents_csv'),



   


   #### Country
   path('create_country/', country.create_country, name='create_country'),
   path('country_statistics/', country.country_statistics, name='country_statistics'),
    path('export_countries_csv/', country.export_countries_csv, name='export_countries_csv'),
     path('countries/<slug:slug>/', country.country_detail, name='country_detail'),
    
    path('countries/<slug:slug>/update/', country.update_country, name='update_country'),
    
    path('countries/<slug:slug>/delete/', country.delete_country, name='delete_country'),
    path('download_sample_countries_csv/', country.download_sample_countries_csv, name='download_sample_countries_csv'),
    path('upload_countries_csv/', country.upload_country_csv, name='upload_countries_csv'),
        path('export_all_countries_csv/', country.export_all_countries_csv, name='export_all_countries_csv'),



    



]

locations/models.py
from django.db import models  # استيراد وحدة النماذج لإنشاء نماذج قواعد البيانات في Django
from django.utils.text import slugify  # استيراد وظيفة لتحويل النصوص إلى صيغة مناسبة لعناوين URL
from django.utils.translation import gettext_lazy as _  # استيراد وحدة الترجمة لدعم الترجمات
from django.dispatch import receiver  # استيراد وحدة استقبال الإشارات لربطها بدوال محددة
from accounts.models import Employee  # استيراد نموذج "Employee" من تطبيق "accounts" لاستخدامه
from django.db.models.signals import post_save, pre_delete, post_delete, pre_save
from django.dispatch import receiver
from django.utils.timezone import now
from django.dispatch import receiver
from django.forms.models import model_to_dict
from accounts.models import Employee



# نموذج مجرد يحتوي على الحقول الزمنية
class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("تم الإنشاء في"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("تم التحديث في"))

    class Meta:
        abstract = True
        verbose_name = _("نموذج الطابع الزمني")


# نموذج مجرد مع حقل slug
class SluggedModel(models.Model):
    slug = models.SlugField(
        max_length=100, unique=True, blank=True, null=True,
        verbose_name=_("الـ slug"), help_text=_("الـ slug يتم إنشاؤه تلقائيًا من الاسم إذا لم يتم توفيره")
    )

    class Meta:
        abstract = True

    def generate_unique_slug(self, name_field):
        slug_candidate = slugify(name_field)
        original_slug = slug_candidate
        counter = 1
        while self.__class__.objects.filter(slug=slug_candidate).exclude(pk=self.pk).exists():
            slug_candidate = f"{original_slug}-{counter}"
            counter += 1
        return slug_candidate
    

# نموذج المحافظات
class Governorate(TimestampedModel, SluggedModel):
    created_by = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, verbose_name=_("الموظف"))
    name_english = models.CharField(max_length=100, unique=True, null=True, blank=True, verbose_name=_("المحافظة بالإنجليزية"))
    name_arabic = models.CharField(max_length=100, unique=True, verbose_name=_("المحافظة بالعربية"))
    description = models.TextField(blank=True, verbose_name=_("الوصف"))

    class Meta:
        verbose_name = _("المحافظة")
        verbose_name_plural = _("المحافظات")
        permissions = [
            ("can_view_governorate_details", _("عرض تفاصيل المحافظة")),
            ("can_reate_governorate", _("اضافة المحافظة")),
            ("can_update_governorate", _("تحديث المحافظة")),
            ("can_delete_governorate", _("حذف المحافظة")),
        ]

    def __str__(self):
        return self.name_arabic
    
    def get_description(self):
        return _("يتعامل هذا الجدول مع المحافظات  من حيث الاضافة والحذف والتحديث")


# نموذج المناطق
class Region(TimestampedModel, SluggedModel):
    name_english = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("الاسم بالإنجليزية"))
    name_arabic = models.CharField(max_length=100, verbose_name=_("الاسم بالعربية"))
    governorate = models.ForeignKey(Governorate, on_delete=models.CASCADE, verbose_name=_("المحافظة"))
    created_by = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, verbose_name=_("الموظف"))
    description = models.TextField(blank=True, verbose_name=_("الوصف"))

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['governorate', 'name_english'], name='unique_region_per_governorate')
        ]
        verbose_name = _("المنطقة")
        verbose_name_plural = _("المناطق")
        permissions = [
            ("can_view_region_details", _("عرض تفاصيل المناطق")),
            ("can_create_region", _("اضافة منطقة")),
            ("can_update_region", _("تحديث منطقة")),
            ("can_delete_region", _("حذف منطقة")),
        ]

    def __str__(self):
        return f"{self.governorate.name_arabic} - {self.name_arabic}"
    
    def get_description(self):  # دالة لإرجاع وصف تفصيلي للمنطقة
        return _("يتعامل هذا الجدول مع المناطق في داخل المحافظات من حيث الإضافة والحذف والتحديث")  # وصف تفصيلي حول الغرض من النموذج


# نموذج القارات
class Continent(TimestampedModel, SluggedModel):
    created_by = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, verbose_name=_("الموظف"))
    name_english = models.CharField(max_length=255, unique=True, verbose_name=_("القارة بالإنجليزية"))
    name_arabic = models.CharField(max_length=255, unique=True, verbose_name=_("القارة بالعربية"))
    description = models.TextField(blank=True, verbose_name=_("الوصف"))

    class Meta:
        verbose_name = _("القارة")
        verbose_name_plural = _("القارات")
        ordering = ['name_english']
        permissions = [
            ("can_view_continent", _("عرض تفاصيل القارات")),
            ("can_create_continent", _(" القدرة على اضافة  قارة")),
            ("can_update_continent", _(" القدرة على تحديث القارات")),
            ("can_delete_continent", _("القدرة على حذف  القارات")),
           
        ]

    def __str__(self):
        return self.name_arabic
    
    def get_description(self):  # دالة لإرجاع وصف تفصيلي للمنطقة
        return _("يتعامل هذا الجدول مع القارات من حيث الإضافة والحذف والتحديث")  # وصف  للغرض من النموذج

# نموذج الدول
class Country(TimestampedModel, SluggedModel):
    created_by = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, verbose_name=_("الموظف"))
    name_english = models.CharField(max_length=255, null=True, blank=True, verbose_name=_("الدولة بالإنجليزية"))
    name_arabic = models.CharField(max_length=255, unique=True, verbose_name=_("الدولة بالعربية"))
    description = models.TextField(null=True, blank=True, verbose_name=_("الوصف"))
    continent = models.ForeignKey(Continent, null=True, blank=True, on_delete=models.CASCADE, verbose_name=_("القارة"))

    class Meta:
        verbose_name = _("الدولة")
        verbose_name_plural = _("الدول")
        ordering = ['name_english']
        unique_together = [ 'name_arabic']
        permissions = [
            ("can_view_country_details", _("عرض تفاصيل الدول")),
            ("can_create_country", _("اضافة دول")),
            ("can_update_country", _("تحديث الدول")),
            ("can_delete_country", _("حذف الدول")),
        ]


    def __str__(self):
        return f"{self.name_arabic} ({self.name_english})"
    
    def get_description(self):  # دالة لإرجاع وصف تفصيلي للمنطقة
        return _("يتعامل هذا الجدول مع الدول من حيث الإضافة والحذف والتحديث")  # وصف  للغرض من النموذج


@receiver(pre_save, sender=Governorate)  # استقبال الإشارة لنموذج Governorate
@receiver(pre_save, sender=Region)  # استقبال الإشارة لنموذج Region
@receiver(pre_save, sender=Continent)  # استقبال الإشارة لنموذج Continent
@receiver(pre_save, sender=Country)  # استقبال الإشارة لنموذج Country
def update_slug(sender, instance, *args, **kwargs):
    """Update slug field before saving."""
    source_value = getattr(instance, 'name_english', None)  # الحصول على القيمة من الحقل name_english

    # توليد slug فقط إذا كانت القيمة موجودة
    if source_value:  # إذا كانت القيمة موجودة
        new_slug = instance.generate_unique_slug(source_value)  # توليد slug فريد
        if instance.slug != new_slug:  # إذا كان الـ slug الحالي مختلفًا عن الجديد
            instance.slug = new_slug  # تحديث قيمة الـ slug في الكائن


####################### Log changes ###################



# نموذج سجل تغييرات المحافظات
class GovernorateChangeLog(models.Model):
    governorate = models.ForeignKey(
        Governorate,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="change_logs",
        verbose_name=_("معلومات المحافظة")
    )
    action = models.CharField(
        max_length=20,
        choices=[
            ('create', 'إضافة'),
            ('update', 'تعديل'),
            ('delete', 'حذف'),
        ],
        verbose_name=_("نوع العملية")
    )
    field_name = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name=_("اسم الحقل")
    )
    old_value = models.TextField(
        null=True,
        blank=True,
        verbose_name=_("القيمة القديمة")
    )
    new_value = models.TextField(
        null=True,
        blank=True,
        verbose_name=_("القيمة الجديدة")
    )
    user = models.ForeignKey(
        Employee,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("المستخدم المسؤول")
    )
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=_("وقت التغيير"))

    class Meta:
        verbose_name = _("سجل تغييرات المحافظة")
        verbose_name_plural = _("سجلات تغييرات المحافظات")
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.governorate} - {self.action} - {self.timestamp}"


# نموذج سجل تغييرات المناطق
class RegionChangeLog(models.Model):
    region = models.ForeignKey(
        Region,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="change_logs",
        verbose_name=_("معلومات المنطقة")
    )
    action = models.CharField(
        max_length=20,
        choices=[
            ('create', 'إضافة'),
            ('update', 'تعديل'),
            ('delete', 'حذف'),
        ],
        verbose_name=_("نوع العملية")
    )
    field_name = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name=_("اسم الحقل")
    )
    old_value = models.TextField(
        null=True,
        blank=True,
        verbose_name=_("القيمة القديمة")
    )
    new_value = models.TextField(
        null=True,
        blank=True,
        verbose_name=_("القيمة الجديدة")
    )
    user = models.ForeignKey(
        Employee,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("المستخدم المسؤول")
    )
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=_("وقت التغيير"))

    class Meta:

locations/forms.py
# forms.py
from django import forms
from .models import Governorate, Region, Continent, Country

class GovernorateForm(forms.ModelForm):
    class Meta:
        model = Governorate
        fields = ['name_english', 'name_arabic', 'description']

class GovernorateCSVUploadForm(forms.Form):
    csv_file = forms.FileField(
        label="رفع ملف CSV",
        help_text="يرجى رفع ملف بصيغة CSV فقط.",
    )

class RegionForm(forms.ModelForm):
    class Meta:
        model = Region
        fields = ['governorate', 'name_english', 'name_arabic', 'description']

class RegionCSVUploadForm(forms.Form):
    csv_file = forms.FileField(
        label="رفع ملف CSV",
        help_text="يرجى رفع ملف بصيغة CSV يحتوي على البيانات المطلوبة للمناطق."
    )

class ContinentForm(forms.ModelForm):
    class Meta:
        model = Continent
        fields = ['name_english', 'name_arabic']


class CountryCSVUploadForm(forms.Form):
    csv_file = forms.FileField(
        label="رفع ملف CSV",
        help_text="يرجى رفع ملف بصيغة CSV يحتوي على البيانات المطلوبة."
    )

      

class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ['continent', 'name_english', 'name_arabic']

locations/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from django.db.models import Count
from .models import Governorate, Region, Continent, Country

def main_locations_dashboard(request):
    total_governorates = Governorate.objects.count()

    # Query to get governorates with the most regions
   
    # Query to get the total number of regions
    total_regions = Region.objects.count()

    # Query to get the total number of continents
    total_continents = Continent.objects.count()

    # Query to get the total number of countries
    total_countries = Country.objects.count()

    # Query to get the most recent governorates
    recent_governorates = Governorate.objects.order_by('-created_at')[:1]


    recent_regions = Region.objects.order_by('-created_at')[:1]

    recent_continents = Continent.objects.order_by('-created_at')[:1]

    recent_countries = Country.objects.order_by('-created_at')[:1]

    context = {
        'total_governorates': total_governorates,
        
        'total_regions': total_regions,
        'total_continents': total_continents,
        'total_countries': total_countries,
        'recent_governorates': recent_governorates,
        'recent_regions': recent_regions,
        'recent_countries': recent_countries,
        'recent_continents': recent_continents,
    }

    return render(request, 'locations/main_locations_dashboard.html', context)

locations/templates/locations/country/country_detail.html
{% extends 'core/base.html' %}

{% block titlecontent %} {% endblock %}

{% block content %}
<h2>تفاصيل الدولة: {{ country.name_arabic }}</h2>

<p>اسم الدولة بالإنكليزي: {{ country.name_english }}</p>
<p>اسم القارة: {{ country.continent.name_arabic }}</p>
<p>الوصف: {{ country.description }}</p>
<p>مدخل البيانات: {{ country.created_by.get_full_name }}</p>
<p>تاريخ إنشاء البيانات: {{ country.created_at }}</p>
<p>تاريخ تحديث البيانات: {{ country.updated_at }}</p>

<a href="{% url 'locations:update_country' country.slug %}" class="update_button">تحديث الدولة</a>
<a href="{% url 'locations:delete_country' country.slug %}" class="delete_button" onclick="return confirm('هل أنت متأكد أنك تريد حذف هذه الدولة')">حذف</a>


{% endblock %}


{% block leftsidemenu %}
<label class="result-label">   {{ request.user }}</label>
{% endblock %}


{% block sidemenu %}

<div class="button-container">

<a href="{% url 'locations:main_locations_dashboard' %}" class="custom-button">الاماكن</a>
<a href="{% url 'locations:country_statistics' %}" class="custom-button">صفحة الدول</a>




</div>


{% endblock %}

locations/templates/locations/country/country_form.html
  {% extends 'core/base.html' %}

  {% block titlecontent %}احصائيات الدول{% endblock %}
  
  {% block sidemenu %}
  
      
  
  {% endblock %}
  
  {% block content %}
  <h2> ادخال دولة</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>

  {% endblock %}
  

locations/templates/locations/country/country_statistics.html
{% extends 'core/base.html' %}

{% block searchbar %}
<!-- يمكن إضافة مربع بحث هنا إن لزم -->
{% endblock %}

{% block titleleftsidemenu %}
<!-- يمكن تركه فارغاً أو وضع عنوان مناسب -->
{% endblock %}

{% block leftsidemenu %}
<label class="result-label">عدد الدول: {{ total_countries }}</label>
{% endblock %}

{% block titlecontent %}إحصائيات الدول{% endblock %}

{% block sidemenu %}
<div class="button-container">
    <a href="{% url 'locations:main_locations_dashboard' %}" class="custom-button">الأماكن</a>
    {% if perms.locations.can_create_country %}
    <a href="{% url 'locations:create_country' %}" class="custom-button">إدخال دولة جديدة</a>
    {% endif %}
    <a href="{% url 'locations:export_countries_csv' %}?continent={{ selected_continent }}" class="custom-button">تصدير CSV</a>

    <a href="{% url 'locations:download_sample_countries_csv' %}" class="custom-button">نموذج CSV</a>

    <a href="{% url 'locations:upload_countries_csv' %}" class="custom-button">رفع CSV</a>

    
</div>
{% endblock %}

{% block content %}
<h2>إحصائيات الدول</h2>
<div class="table-container">
    <table class="creative-table">
        <thead>
            <tr>
                <th>#</th>
                <th>اسم القارة بالعربي</th>
                <th>اسم الدولة بالعربي</th>
                <th>اسم الدولة بالإنجليزي</th>
                <th>مدخل الدولة</th>
                <th>ملاحظات</th>
                <th>عرض التفاصيل</th>
                <th>تحديث</th>
                <th>حذف</th>
            </tr>
        </thead>
        <tbody>
            {% for country in countries %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ country.continent.name_arabic }}</td>
                <td>{{ country.name_arabic }}</td>
                <td>{{ country.name_english }}</td>
                <td>{{ country.created_by }}</td>
                <td>{{ country.description }}</td>
                <td>
                    {% if perms.locations.can_view_country_details %}
                    <a href="{% url 'locations:country_detail' country.slug %}" class="update_button">عرض</a>
                    {% else %}ليس لديك صلاحية{% endif %}
                </td>
                <td>
                    {% if perms.locations.can_update_country %}
                    <a href="{% url 'locations:update_country' country.slug %}" class="update_button">تحديث</a>
                    {% else %}ليس لديك صلاحية{% endif %}
                </td>
                <td>
                    {% if perms.locations.can_delete_country %}
                    <a href="{% url 'locations:delete_country' country.slug %}" class="delete_button" onclick="return confirm('هل أنت متأكد أنك تريد حذف هذه الدولة؟')">حذف</a>
                    {% else %}ليس لديك صلاحية{% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="9">لا توجد دول مسجلة حالياً.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block pagination %}
<div class="pagination-container">
    <div class="pagination-info">
        <span>عدد العناصر بالصفحة:</span>
        <form method="get" action="" class="pagination-form">
            <input type="number" id="results_per_page" name="results_per_page" placeholder="عدد النتائج لكل صفحة" value="{{ results_per_page }}" class="pagination-input">
        </form>
    </div>
    <div class="pagination-controls">
        {% if countries.has_previous %}
            <a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page=1" class="pagination-button">الأولى</a>
            <a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ countries.previous_page_number }}" class="pagination-button">السابق</a>
        {% endif %}
        <span>صفحة {{ countries.number }} من {{ countries.paginator.num_pages }}</span>
        {% if countries.has_next %}
            <a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ countries.next_page_number }}" class="pagination-button">التالي</a>
            <a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ countries.paginator.num_pages }}" class="pagination-button">الأخيرة</a>
        {% endif %}
    </div>
</div>
{% endblock %}

locations/templates/locations/country/update_country.html
{% extends 'core/base.html' %}

{% block titlecontent %} {% endblock %}

{% block content %}
<h2>تحديث الدولة: {{ country.name_arabic }}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="update_button">حفظ التغييرات</button>
</form>



{% endblock %}


{% block sidemenu %}

<div class="button-container">

<a href="{% url 'locations:main_locations_dashboard' %}" class="custom-button">الاماكن</a>
<a href="{% url 'locations:country_statistics' %}" class="custom-button">صفحة الدول</a>




</div>


{% endblock %}

{% block leftsidemenu %}
<label class="result-label">   {{ request.user }}</label>
{% endblock %}

locations/templates/locations/country/upload_countries_csv.html
{% extends 'core/base.html' %}


{% block searchbar %}


{% endblock %}

{% block titleleftsidemenu %}


{% endblock %}

{% block leftsidemenu %}
<label class="result-label">   {{ request.user }}</label>
{% endblock %}


{% block titlecontent %}

{% endblock %}




{% block content %}
<h2>  CSV المحافظات</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="update_button">رفع الملف</button>
</form>
{% endblock %}

{% block pagination %}

{% endblock %}



{% block titlesidemenu %}

{% endblock %}



{% block sidemenu %}

<div class="button-container">

<a href="{% url 'locations:main_locations_dashboard' %}" class="custom-button">الاماكن</a>
<a href="{% url 'locations:continent_statistics' %}" class="custom-button">صفحة الدول</a>




</div>


{% endblock %}